
title = "Rsvper"
baseURL = "/"
languageCode = "en-us"
theme = "airspace-hugo"

# The site's parameters
[params]

  # Google Analitycs
  googleAnalitycsID = "Your ID"
  description = "Rsvper is an AI chatbot that handles all your RSVPs for you."
  author = "Shruti Patel"
  
  
  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

# Multilangual : FR / EN
[Languages]
  ######## english language
  [Languages.en]
  languageName = ""
    weight = 2
    languageCode = "en-us"
    title = "Rsvper"
    dateFormat = "January 2, 2006"
    home = "Home"

    
  [Languages.en.menu]

    [[Languages.en.menu.header]]
      weight = 5
      name = "Contact"
      url = "/contact"

    # [[Languages.en.menu.footer]]
    #   weight = 1
    #   name = "About us"
    #   url = "#"
    [[Languages.en.menu.footer]]
      weight = 2
      name = "Contact us"
      url = "#"
    # [[Languages.en.menu.footer]]
    #   weight = 3
    #   name = "How it works"
    #   url = "#"
    # [[Languages.en.menu.footer]]
    #   weight = 5
    #   name = "Terms"
    #   url = "#"

  [Languages.en.params.slider]
    enable = true
    title = "RSVPER"
    subtitle = "We handle the invites and rsvps, so you can spend time on more important things in life."
    bgImage = "img/slider-bg.webp"
    bgImageAlt = "img/slider-bg.jpg"

  # [Languages.en.params.wrapper]
  #   enable = true
  #   image = "img/wrapper-img.png"
  #   title = "About Us"
  #   italic = "We handle the invites and rsvps, so you can spend time on more important things in life."
  #   paragraph = "We help "

  # [Languages.en.params.blog]
  #   enable = true
  #   title = "Get The Latest On What We're doing"
  #   subtitle = "Catch up with us, anytime and anywhere"

  # [Languages.en.params.feature]
  #   enable = true
  #   title = "We believe in great ideas"
  #   bgImage = "img/feature-bg.webp"
  #   bgImageAlt = "img/feature-bg.jpg"
  #   content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
  #   [Languages.en.params.feature.button]
  #     caption = "View Works"
  #     url = "#"

  [Languages.en.params.call]
    enable = true
    bgImage = "img/call-to-action-bg.jpg"
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [Languages.en.params.contact]
    enable = true
    title = "Drop us a note"
    # subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [Languages.en.params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    # [Languages.en.params.contact.box]
    #   title = "Stop by for a visit"
    #   address = "North Main Street, Brooklyn Australia"
    #   email = "Email: contact@mail.com"
    #   phone = "Phone: +88 01672 506 744"
    # [Languages.en.params.contact.gmaps]
    #   title = "We Also Count in Google Maps"
